name: Composite Workflow
description: Composite workflow without inputs
runs:
  using: composite
  steps:
    - name: Install nodejs runtime
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
